import frappe
try:
    import yaml
    YAML_AVAILABLE = True
except ImportError:
    YAML_AVAILABLE = False

@frappe.whitelist(xss_safe=False)
def get_openapi_spec():
    try:
        app_name = frappe.form_dict.get('app')
        format_type = frappe.form_dict.get('format', 'json')
        
        from api_explorer.core.scanner.manager import APIScanner
        scanner = APIScanner()
        api_data = scanner.scan_all_apis()
        
        spec = {
            "openapi": "3.0.3",
            "info": {
                "title": f"{app_name} APIs" if app_name else "Frappe APIs",
                "description": "API documentation generated by API Explorer",
                "version": "1.0.0",
                "contact": {"name": "API Support", "url": frappe.utils.get_url()}
            },
            "servers": [{"url": frappe.utils.get_url(), "description": "Current Site"}],
            "paths": {},
            "components": {
                "securitySchemes": {
                    "ApiKeyAuth": {"type": "apiKey", "in": "header", "name": "Authorization", "description": "Format: 'token <api_key>:<api_secret>'"}
                },
                "schemas": {
                    "SuccessResponse": {
                        "type": "object",
                        "properties": {"message": {"description": "Response data"}}
                    },
                    "ErrorResponse": {
                        "type": "object",
                        "properties": {
                            "exc_type": {"type": "string"},
                            "exception": {"type": "string"},
                            "_server_messages": {"type": "string"}
                        }
                    }
                }
            },
            "security": [{"ApiKeyAuth": []}]
        }
        
        apps = api_data.get("apps", {})
        if app_name and app_name in apps:
            apps = {app_name: apps[app_name]}
        
        for app, categories in apps.items():
            for category, apis in categories.items():
                if isinstance(apis, list):
                    for api in apis:
                        api_path = api.get('path', '')
                        path = f"/api/method/{api_path}"
                        if path not in spec["paths"]:
                            spec["paths"][path] = {}
                        
                        # Build request body from parameters
                        request_body = {"type": "object", "properties": {}}
                        required_params = []
                        
                        for param in api.get('parameters', []):
                            param_name = param.get('name') if isinstance(param, dict) else param
                            param_type = param.get('type', 'string') if isinstance(param, dict) else 'string'
                            param_desc = param.get('description', '') if isinstance(param, dict) else ''
                            is_required = param.get('required', False) if isinstance(param, dict) else False
                            
                            request_body["properties"][param_name] = {
                                "type": param_type,
                                "description": param_desc or f"Parameter {param_name}"
                            }
                            if is_required:
                                required_params.append(param_name)
                        
                        if required_params:
                            request_body["required"] = required_params
                        
                        operation = {
                            "operationId": api_path.replace('.', '_'),
                            "summary": api.get("name", "API Endpoint"),
                            "description": api.get('docstring', f"API from {app} - {category}"),
                            "tags": [f"{app}-{category}"],
                            "responses": {
                                "200": {
                                    "description": "Successful response",
                                    "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SuccessResponse"}}}
                                },
                                "400": {
                                    "description": "Bad Request",
                                    "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}
                                },
                                "401": {"description": "Unauthorized - Invalid or missing authentication"},
                                "403": {"description": "Forbidden - Insufficient permissions"},
                                "500": {
                                    "description": "Internal Server Error",
                                    "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}
                                }
                            }
                        }
                        
                        # Add request body if parameters exist
                        if request_body["properties"]:
                            operation["requestBody"] = {
                                "required": bool(required_params),
                                "content": {
                                    "application/json": {"schema": request_body},
                                    "application/x-www-form-urlencoded": {"schema": request_body}
                                }
                            }
                        
                        spec["paths"][path]["post"] = operation
        
        if format_type == 'yaml' and YAML_AVAILABLE:
            frappe.local.response.headers['Content-Type'] = 'application/x-yaml'
            return yaml.dump(spec, default_flow_style=False, sort_keys=False)
        
        return spec
    except Exception as e:
        frappe.log_error(f"OpenAPI Error: {str(e)}")
        return {"error": "Failed to generate OpenAPI spec", "message": str(e)}

@frappe.whitelist(xss_safe=False)
def get_api_schema():
    try:
        api_path = frappe.form_dict.get('api_path')
        if not api_path:
            return {"error": "API path is required"}
        
        # Try to get actual function details
        try:
            func = frappe.get_attr(api_path)
            import inspect
            
            # Get docstring
            docstring = inspect.getdoc(func) or f"API endpoint: {api_path}"
            
            # Get parameters for OpenAPI format
            request_body = {"type": "object", "properties": {}}
            
            try:
                sig = inspect.signature(func)
                for param_name, param in sig.parameters.items():
                    if param_name not in ['self', 'cls']:
                        param_schema = {
                            "type": "string",
                            "description": f"Parameter {param_name}"
                        }
                        if param.default != inspect.Parameter.empty:
                            param_schema["default"] = str(param.default)
                        
                        request_body["properties"][param_name] = param_schema
                        
                        if param.default == inspect.Parameter.empty:
                            if "required" not in request_body:
                                request_body["required"] = []
                            request_body["required"].append(param_name)
            except:
                pass
            
            return {
                "openapi": "3.0.3",
                "info": {
                    "title": f"API: {api_path}",
                    "description": "Single API endpoint documentation",
                    "version": "1.0.0"
                },
                "servers": [{"url": frappe.utils.get_url(), "description": "Current Site"}],
                "paths": {
                    f"/api/method/{api_path}": {
                        "post": {
                            "operationId": api_path.replace('.', '_'),
                            "summary": api_path.split(".")[-1],
                            "description": docstring,
                            "tags": [api_path.split(".")[0] if "." in api_path else "API"],
                            "requestBody": {
                                "required": bool(request_body.get("required")),
                                "content": {
                                    "application/json": {"schema": request_body},
                                    "application/x-www-form-urlencoded": {"schema": request_body}
                                }
                            } if request_body["properties"] else None,
                            "responses": {
                                "200": {
                                    "description": "Successful response",
                                    "content": {
                                        "application/json": {
                                            "schema": {
                                                "type": "object",
                                                "properties": {
                                                    "message": {"description": "Response data"}
                                                }
                                            }
                                        }
                                    }
                                },
                                "400": {
                                    "description": "Bad Request - Invalid parameters",
                                    "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}
                                },
                                "401": {"description": "Unauthorized - Invalid or missing authentication"},
                                "403": {"description": "Forbidden - Insufficient permissions"},
                                "500": {
                                    "description": "Internal Server Error",
                                    "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}
                                }
                            },
                            "security": [{"ApiKeyAuth": []}]
                        }
                    }
                },
                "components": {
                    "securitySchemes": {
                        "ApiKeyAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Format: 'token <api_key>:<api_secret>'"
                        }
                    },
                    "schemas": {
                        "ErrorResponse": {
                            "type": "object",
                            "properties": {
                                "exc_type": {"type": "string", "description": "Exception type"},
                                "exception": {"type": "string", "description": "Error message"},
                                "_server_messages": {"type": "string", "description": "Server messages"}
                            }
                        }
                    }
                }
            }
            
        except Exception as func_error:
            return {
                "openapi": "3.0.3",
                "info": {
                    "title": f"API: {api_path}",
                    "description": "API endpoint documentation",
                    "version": "1.0.0"
                },
                "servers": [{"url": frappe.utils.get_url(), "description": "Current Site"}],
                "paths": {
                    f"/api/method/{api_path}": {
                        "post": {
                            "operationId": api_path.replace('.', '_'),
                            "summary": api_path.split(".")[-1],
                            "description": f"API endpoint: {api_path}",
                            "tags": [api_path.split(".")[0] if "." in api_path else "API"],
                            "responses": {
                                "200": {
                                    "description": "Successful response",
                                    "content": {"application/json": {"schema": {"type": "object", "properties": {"message": {"description": "Response data"}}}}}
                                },
                                "400": {"description": "Bad Request"},
                                "401": {"description": "Unauthorized"},
                                "403": {"description": "Forbidden"},
                                "500": {"description": "Internal Server Error"}
                            },
                            "security": [{"ApiKeyAuth": []}]
                        }
                    }
                },
                "components": {
                    "securitySchemes": {
                        "ApiKeyAuth": {"type": "apiKey", "in": "header", "name": "Authorization", "description": "Format: 'token <api_key>:<api_secret>'"}
                    }
                }
            }
    except Exception as e:
        frappe.log_error(f"API Schema Error: {str(e)}")
        return {"error": "Failed to get API schema", "message": str(e)}